#+TITLE:     
#+AUTHOR:    David Mann
#+EMAIL:     mannd@epstudiossoftware.com
#+DATE:      [2015-04-09 Thu]
#+DESCRIPTION: EP Calipers Help for Android
#+KEYWORDS:
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:nil toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 
#+XSLT:
* Overview
*EP Calipers* provides electronic calipers for measuring intervals on images of electrocardiograms (ECGs) or electrophysiologic recordings.  It is common for doctors, nurses and medical technicians to take pictures of ECGs and send them to each other using smart phones and tablets.  It is more difficult to make measurements on these images than it is on paper ECG recordings.  *EP Calipers* makes these measurements very accurately and can calculate mean heart rates and corrected QT intervals using electronic calipers similar to those in electrophysiologic recording systems.
* Using the calipers
** It's intuitive
When *EP Calipers* starts, a sample ECG and a time caliper are loaded.
Move the caliper around by touching the caliper's cross-bar and
dragging it with your finger.  Expand and contract the caliper by
putting your finger on either vertical bar and dragging.  Pinch and
zoom the underlying ECG image as needed.  If the ECG is bigger than
your screen, you can drag the image around with your finger.
Double-tap the ECG image to rapidly zoom in and out.  The remainder of
these instructions will go over how to load ECG images, add and delete
calipers, calibrate the calipers and make advanced measurements like
the corrected QT interval.
** Loading an image
Use the *Switch* or *Switch Mode* button at the top right of the
screen to show the *Image* menu at the botton of your screen.  With
this menu you can load and fine-tune an ECG image. Touch the *Camera*
button to take a photo of an ECG tracing and load it into the app.
Alternatively, Touch *Select* to chose an image that is already saved
on your device.  Tap *Switch* again to go back to making measurements.
** Adjusting the image
As always you can adjust the positioning of the image using
pinch-to-zoom, dragging, and double-tapping while in *Image mode*.
You cannot adjust the calipers while in *Image Mode*. Use the *Adjust*
menu to rotate the image.  When you are done adjusting your image go
back to making measurements by tapping *Switch*.
** Moving calipers
Drag the crossbar of a caliper to move it as a unit.  Drag the left or right bars (or top or bottom in the case of vertical calipers) to stretch or shrink the calipers.  Note that you cannot pinch both bars at the same time.
** Making measurements
The interval measured by each caliper is displayed over the crossbar of the caliper.  Until the calipers are calibrated, measurements are displayed in arbitrary units ("points").
** Adding and deleting calipers
Select the *+* or *Add Caliper* icon to add new calipers.  Calipers can be horizontal (time measurements) or vertical (amplitude measurements).  Select *Time* or *Amplitude* to add the type of caliper you want.  Double-tap a caliper to delete it.
** Selecting a caliper
When more than one caliper is present, it is necessary that one is selected to be the active caliper when calibrating or making calculated measurements.  By default an unselected caliper is blue and a selected caliper is red (You can change these colors if you want).  Single tapping an unselected caliper will select it.  Tap it again (but not too fast, as a double tap deletes the caliper) will unselect it.  As there can be only one selected caliper at a time, selecting a caliper will unselect any other caliper that happens to be selected.  In some cases a caliper will be selected automatically (for example to do calibration) if you have not already selected one.  If you want to select a different caliper, just tap another caliper.
** Calibration
Select *Cal* or *Calibrate*.  Stretch a highlighted caliper over a known interval (such as 1000 msec for time, or 10 mm for amplitude calipers).  Select *Set*.  In the dialog box, make sure the interval matches what you are measuring.  It is best if you enter both the calibration interval and units (e.g. 500 msec or 1 sec or 1 mV).  Select *Set* in the dialog box to set the calibration.  Time and amplitude calipers need to be calibrated separately.  Once calibrated, calipers will show intervals in the units used to calibrate.  Newly created calipers will use the same calibration.
** Changing calibration
You can recalibrate at any time.  You can clear all calibration by selecting *Clear* in the calibration toolbar.  Note that calibration is maintained if the device is rotated, shifted, or zoomed.  Selecting a new image will reset calibration.
** Interval/Rate
Once a time (horizontal) caliper is calibrated, provided you use time units (such as msec or sec) for the calibration, it is possible to toggle between interval measurements (e.g. 600 msec) and heart rate measurements (e.g. 100 bpm) by selecting *Interval/Rate* or *I/R*.
** Mean rate and interval calculation
Select a calibrated caliper and stretch it over a number of intervals. Select *Mean Rate* or *mRate* and enter the number of intervals measured.  A dialog box will show the calculated mean heart rate and interval.  This is useful for calculating rates and intervals in irregular rhythms, such as atrial fibrillation.
** QTc calculation
Stretch a time caliper over one or more intervals and select *QTc*.  Follow the prompts.  After measuring the interval/rate, measure the QT.  A dialog box will give the calculated QTc using Bazett's formula.
** Settings
Preferences such as caliper colors and default calibration intervals can be selected using the *Settings* menu item on the toolbar at the top of the app.
** Device rotation
Caliper calibration as well as scaling and rotation of the ECG image are maintained with device rotation.  Calipers may need to be repositioned after device rotation.  If the device is rotated in the middle of doing the steps of the QTc calculation it will be necessary to start the calculation over.
* Acknowledgements
- Thanks to Dr. Michael Katz for suggesting the concept.
- The source code for *EP Calipers* is available on [[https://github.com/mannd/epcalipers-android][GitHub]].
- *EP Calipers* is open source software and is licensed under the [[https://www.gnu.org/copyleft/gpl.html][GNU
  General Public License version 3]].  No guarantees are made as to the
  accuracy of the app, so use at your own risk.
- For questions, error reporting or suggestions contact
  [[mailto:mannd@epstudiossoftware.com][EP Studios]].
- Website: [[http://www.epstudiossoftware.com][epstudiossoftware.com]]
