#+TITLE:     
#+AUTHOR:    David Mann
#+EMAIL:     mannd@epstudiossoftware.com
#+DATE:      [2015-04-09 Thu]
#+DESCRIPTION: EP Calipers Help for Android
#+KEYWORDS:
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:nil toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 
#+XSLT:
* Overview
*EP Calipers* provides electronic calipers to measure intervals on images of ECGs or electrophysiologic recordings.  In today's practice of medicine, it is common for doctors, nurses and medical technicians to photograph and send ECGs to each other via email and messaging using smart phones and tablets.  It is more difficult to make measurements on these images than it is with ECG recordings made on paper.  *EP Calipers* can be used to make these measurements and do these calculations, using electronic calipers similar to those in electrophysiologic recording systems.
* Using the calipers
** EP Calipers Mode versus Image Mode
In *EP Calipers* you can manipulate calipers, or manipulate the image,
but not both at the same time.  The title bar at the top of the screen
indicates which mode you are in.  The app starts in *EP Calipers Mode*
(with a sample image loaded).  You can create, delete, and move
calipers, as well as perform calculations such as mean heart rate and
corrected QT interval in this mode.  Selecting *Switch* or *Switch
Mode* (menu items are worded slightly differently depending on the
size of the screen) on the title bar switches to *Image Mode*.  Use
this mode to load an image and zoom or scroll around in the image
using finger gestures.  Switch back to *EP Calipers* mode by selecting
*Switch Mode* again.
** Loading an image
If the title bar doesn't show *Image Mode* touch the *Switch Mode*
button to change modes.  Touch the *Camera* button to take a photo of
an ECG tracing and load it into the app.  Alternatively, Touch
*Select* to chose an image that is already saved on your device.
Select *Done* to return to the main toolbar.
** Adjusting the image
While in *Image Mode* you can adjust the positioning of the image
using pinch-to-zoom or double-tap gestures and finger scrolling.  Use
the *Adjust* menu to rotate the image.
** Moving calipers
Drag the crossbar of a caliper to move it as a unit.  Drag the left or right bars (or top or bottom in the case of vertical calipers) to stretch or shrink the calipers.  Note that you cannot pinch both bars at the same time.
** Making measurements
The interval measured by each caliper is displayed over the crossbar of the caliper.  Until the calipers are calibrated, measurements are displayed in arbitrary units ("points").
** Adding and deleting calipers
Select the *+* or *Add Caliper* icon to add new calipers.  Calipers can be horizontal (time measurements) or vertical (amplitude measurements).  Select *Time* or *Amplitude* to add the type of caliper you want.  Double-tap a caliper to delete it.
** Highlighting a caliper
Single tap a caliper to highlight it.  Its color will change.  Tap another caliper to change the highlight to that caliper.  Only one caliper can be highlighted at a time.  Touch any place where there is not a caliper to remove highlighting.  Tap a highlighted caliper (when not in the middle of a calculation) and it will be deleted. In some cases a caliper will be highlighted automatically (for example to do calibration) if you have not already highlighted one.  If you want to highlight a different caliper, just tap another caliper.  A caliper needs to be highlighted to do calibrations and calculations.
** Calibration
Select *Cal* or *Calibrate*.  Stretch a highlighted caliper over a known interval (such as 1000 msec for time, or 10 mm for amplitude calipers).  Select *Set*.  In the dialog box, make sure the interval matches what you are measuring.  It is best if you enter both the calibration interval and units (e.g. 400 msec or 1 sec or 1 mV).  Select *Set* in the dialog box to set the calibration.  Time and amplitude calipers need to be calibrated separately.  Once calibrated, calipers will show intervals in the units used to calibrate.  Newly created calipers will use the same calibration.
** Changing calibration
You can recalibrate at any time.  You can clear all calibration by selecting *Clear* in the calibration toolbar.  Note that calibration is maintained if the device is rotated, shifted, or zoomed.  Selecting a new image will reset calibration.
** Interval/Rate
Once a time (horizontal) caliper is calibrated, provided you use time units (such as msec or sec) for the calibration, it is possible to toggle between interval measurements (e.g. 600 msec) and heart rate measurements (e.g. 100 bpm) by selecting *Interval/Rate* or *I/R*.
** Mean rate and interval calculation
Select a calibrated caliper and stretch it over a number of intervals. Select *Mean Rate* or *mRate* and enter the number of intervals measured.  A dialog box will show the calculated mean heart rate and interval.  This is useful for calculating rates and intervals in irregular rhythms, such as atrial fibrillation.
** QTc calculation
Stretch a time caliper over one or more intervals and select *QTc*.  Follow the prompts.  After measuring the interval/rate, measure the QT.  A dialog box will give the calculated QTc using Bazett's formula.
** Settings
Preferences such as caliper colors and default calibration intervals can be selected using the *Settings* menu item on the toolbar at the top of the app.
** Device rotation
Caliper calibration as well as scaling and rotation of the ECG image are maintained with device rotation.  Calipers may need to be repositioned after device rotation.  If the device is rotated in the middle of doing the steps of the QTc calculation it will be necessary to start the calculation over.
* Acknowledgements
- Thanks to Dr. Michael Katz for suggesting the idea.
- The source code for *EP Calipers* is available on [[https://github.com/mannd/epcalipers-android][GitHub]].
- *EP Calipers* is open source software and is licensed under the [[https://www.gnu.org/copyleft/gpl.html][GNU
  General Public License version 3]].  No guarantees are made as to the
  accuracy of the app, so use at your own risk.
- For questions, error reporting or suggestions contact
  [[mailto:mannd@epstudiossoftware.com][EP Studios]].
- Website: [[http://www.epstudiossoftware.com][epstudiossoftware.com]]
