

apply plugin: 'com.android.application'

android {
    compileSdkVersion 37

    defaultConfig {
        applicationId "org.epstudios.epcalipers"
        minSdkVersion 21
        targetSdkVersion 37
        versionCode 46
        versionName "3.8.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    buildFeatures {
        buildConfig true
    }
    namespace 'org.epstudios.epcalipers'
}

repositories {
    mavenCentral()
}

allprojects {
    tasks.withType(JavaCompile) {
        options.compilerArgs << "-Xlint:unchecked" << "-Xlint:deprecation"
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'androidx.webkit:webkit:1.17.0'
    implementation 'androidx.appcompat:appcompat:1.8.0'
    implementation 'com.google.android.material:material:1.14.0'
    implementation 'com.github.chrisbanes:PhotoView:2.3.0'
    implementation 'com.github.QuadFlask:colorpicker:0.0.13'
    implementation 'androidx.recyclerview:recyclerview:1.4.0'
    implementation 'com.github.kizitonwose.colorpreference:support:1.1.0'
    // Don't update onboarder.  2.x version uses Kotlin.
    //noinspection GradleDependency
    implementation 'com.cuneytayyildiz:onboarder:2.0.0'
    implementation 'androidx.preference:preference:1.2.1'
    implementation 'androidx.activity:activity:1.13.0'
    // Required for local unit tests (JUnit 4 framework)
    testImplementation 'junit:junit:4.13.2'
    // Required for instrumented tests
    androidTestImplementation 'androidx.annotation:annotation:1.10.0'
    androidTestImplementation 'androidx.test:runner:1.7.0'
    // Required for kotlin activity edge to edge
    implementation("androidx.activity:activity-ktx:1.13.0")
}

dependencies {
//    constraints {
//        implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk7:2.2.10") {
//            because("kotlin-stdlib-jdk7 is now a part of kotlin-stdlib")
//        }
//        implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8:2.2.10") {
//            because("kotlin-stdlib-jdk8 is now a part of kotlin-stdlib")
//        }
//    }
}
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}
